const data = {
    products: [
        {
            _id: '1',
            name: 'Qant Cousin Covers',
            category: 'Cousins',
            image: '/images/cc-1.jpg',
            price: 120,
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Sirra Cousin Covers',
            category: 'Cousins',
            image: '/images/cc-2.jpg',
            price: 200,
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Att Covers',
            category: 'Cousins',
            image: '/images/cc-3.jpg',
            price: 180,
            rating: 4.5,
            numReviews: 40,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Wahh Cousin Covers',
            category: 'Cousins',
            image: '/images/cc-4.jpg',
            price: 100,
            rating: 3.5,
            numReviews: 50,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Qant Sofa Covers',
            category: 'Sofa',
            image: '/images/sc-1.jpg',
            price: 520,
            rating: 4.0,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Sirra Sofa Covers',
            category: 'Sofa',
            image: '/images/sc-2.jpg',
            price: 680,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Att Sofa Covers',
            category: 'Sofa',
            image: '/images/sc-3.jpg',
            price: 800,
            rating: 4.0,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Wahh Sofa Covers',
            category: 'Sofa',
            image: '/images/sc-4.jpg',
            price: 380,
            rating: 3.5,
            numReviews: 70,
            description: 'good quality product',
        },
    ],
};

export default data;